### ISSUE TITLE
Cannot Parse multi-area range formula

### ISSUE THREAD

**Issue by kevinsmith53** [spreadsheetlab/XLParser#124]
The following code will throw an exception. This is a valid formula where we have a range with multiple areas. This type of formula can be created by clicking the 'Define Name' button and then selecting multiple ranges while holding the Ctrl key

`var parseResult = ExcelFormulaParser.Parse("=Sheet1!$A$1,Sheet1!$B$2");`

**Comment by WillemJann** [comment]
A new token `MultiRangeFormula` is added to the grammar, that accepts formulas with a union of ranges. `=A1,A2`, `=A1:A3,C1:C3` and `=Sheet1!$A$1,Sheet1!$B$2` are now valid formulas for XLParser.

(Note that this type of formula must start with an equal sign, to avoid conflicts in the grammar. When you define a name like this in Excel, the formula will automatically start with an equal sign.)

Issue is fixed in commit e11dfb5.
