### ISSUE TITLE
Parse error if file path contains space

### ISSUE THREAD

**Issue by janseba** [spreadsheetlab/XLParser#25]
Got the following parse error in one of the Enron sheets:
Failed parsing input <<`='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301\[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D8`>>

Probably cause by the + in the worksheet name

Got some more:

    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301\[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D8
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D6
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D8
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D7
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]FINANCIAL PIVOT'!D8
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]FINANCIAL PIVOT'!D6
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]FINANCIAL PIVOT'!D8
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]FINANCIAL PIVOT'!D7
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL PIVOT'!D8
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL PIVOT'!D6
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL PIVOT'!D8
    ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL PIVOT'!D7

**Comment by Felienne** [comment]
@aivaloglou I say CAKE :P

**Comment by janseba** [comment]
I would be surprised if this was a new parse error. If it is CAKE indeed.

Gr.

Bas
06-20489516


Op 8 okt. 2015, om 22:01 heeft Felienne <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@aivaloglou<https://github.com/aivaloglou> I say CAKE :P

**Comment by dhoepelman** [comment]
It's not the `+`, it's that it doesn't recognize the filename in between the brackets, I think because of the spaces. Might be hard to fix but I'll take a look

This is in new functionality (parsing filepaths and names) though, does that still count for cake? Also I don't think I ever promised cake :P

**Comment by dhoepelman** [comment]
@janseba I have a fix for this, but not all you formulas parse still. Not because of the space anymore.

Your first two examples parse, but the other ones don't because there seems a `\` missing before the filename:

    This parses:  ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301\[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D6
    This doesn't: ='C:\EOL\Management Report\DATAMART\REGIONAL ANALYSIS\REPORTS\052301[DEAL BREAKDOWN ANALYSIS 05-23-01.xls]PHYSICAL+FINANCIAL PIVOT '!D6

Can you point me to the original enron file or double check that these were indeed the exact formulas?
I might have fucked up your examples when editing your post for clarity, so if that's the case my apoligies.

**Comment by dhoepelman** [comment]
Original file is `andy_zipper__203__DEAL BREAKDOWN ANALYSIS 5-23-01 EM.xlsx`, and it contains the backslashes.
