### ISSUE TITLE
Failed parsing whitespace-only sheet name reference

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#37]
Formula:

```VLOOKUP(' '!G3,' '!B4:F99,5)```

does not parse because of reference to sheet ```' '```

**Comment by Felienne** [comment]
Seriously, the have a sheet with ' ' as a name?! OMG

**Comment by dhoepelman** [comment]
Of course it has.

This one might be a tad difficult to fix too. We need the `SheetQuotedToken` to match this.

    private static readonly string quotedSheetName = $"([^{notSheetNameChars}]|'')+";
    public Terminal SheetQuotedToken = new RegexBasedTerminal(GrammarNames.TokenSheetQuoted, $"{quotedSheetName}'!")


Maybe

     private static readonly string quotedSheetName = $"([^{notSheetNameChars}]|''|\s)+";

**Comment by dhoepelman** [comment]
So what goes wrong is that `'` is recognized, but `'!G3,'` is parsed as if it is a `SingleQuotedString`.
Getting Irony to recognize the ` '!G3` is probably not possible/very hard, since the token would start with a space.

Changing the quotedSheetName to allow empty sheetnames is sortof a fix:

    private static readonly string quotedSheetName = $"([^{notSheetNameChars}]|'')*";

Now `'!G3` is recognized as a token, but the information that the filename is a space is lost.

It would also allow the (probably invalid?) empty sheetname: `''!G3`, and could not discriminate between `' '!G3`, `'  '!G3`, `'      '!G3` etc.

I suggest we still use it, since I don't have a better idea on how to handle it. I can modify the `PrefixInfo` class so it returns a single space as the sheetname in this case (but it will also return this on the empty sheetname, or any sheetname consisting solely of whitespace)

**Comment by aivaloglou** [comment]
I agree with you, it seems like a reasonable workaround.
