### ISSUE TITLE
Failed parsing named range with greek character

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#45]
Formula:

φ * (1-f) * GWP_CH4 * (1-OX) * (16/12) * FF * DOCf * MCF

Apparently, greek characters are allowed.

**Comment by dhoepelman** [comment]
Isn't φ a UDF here? It parses with the changes from #42

It actually still chokes though, because it parses "16" as a SRColumn, probably because it needs reference expressions because it sees intersections.

![image](https://cloud.githubusercontent.com/assets/992153/12292608/83361cae-b9ee-11e5-98f9-9fa468fbc912.png)

I actually don't know what to make from this formula. Implicit multiplication isn't in excel right? (e.g. `5A5` is invalid, not `5*A5`)  
So what does `Function(x)Function(y)(z)NAME` even mean? Because that's how I interpret  the first part `φ(1-f)GWP_CH4(1-OX)(16/12)FFDOCf`

**Comment by aivaloglou** [comment]
Sorry, I just noticed that the ```*```s do not appear. Code markdown also does not work. You can see the original formula in edit mode. φ is a named range and all operations are multiplications.

**Comment by aivaloglou** [comment]
ok, I added some spaces and here it is:

φ * (1-f) * GWP_CH4 * (1-OX) * (16/12) * FF * DOCf * MCF

**Comment by dhoepelman** [comment]
Ah then the parse error is already resolved with #42 :)
