### ISSUE TITLE
Failed parsing named range 

### ISSUE THREAD

**Issue by aivaloglou** [spreadsheetlab/XLParser#46]
Formula:

IF(A2.PART_NUM<>"",(IF(AND(A2.PART_NUM=1),"CO","AP")),"")

does not parse because of named range A2.PART_NUM

**Comment by dhoepelman** [comment]
This is an interesting one. `A2.PART_NUM` should become a `NamedRangeCombinationToken`, but currently the regex is constructed as

    private const string NamedRangeRegex = @"[\p{L}\\_][\w\\_\.\?]*";
    public Terminal NamedRangeCombinationToken = new RegexBasedTerminal(/**/, "(TRUE|FALSE|" + CellTokenRegex + ")" + NamedRangeRegex));

However, that is incorrect, because following something else all characters are allowed, e.g. the name `A1?X` would also choke the parser.

Fix is fairly easy, it push it soon.
