### ISSUE TITLE
Wrong precedence of operator

### ISSUE THREAD

**Issue by wildfire810** [spreadsheetlab/XLParser#50]
I don't know if you understand this issue.
For example, use -1*2, the subtraction is preceding over the multiplication.
Can you fix it?

**Comment by dhoepelman** [comment]
That's because `-1` is a negative number. [Unary minus (listed as negation) has a higher precedence than multiplication](https://support.office.com/en-us/article/Calculation-operators-and-precedence-48be406d-4975-4d31-b2b8-7af9e0e2878a).
So there is nothing to fix.

If you still think it's wrong please provide an example where the precedence produces a different result.

**Comment by wildfire810** [comment]
Thanks
