### ISSUE TITLE
Parse failure: Named range with multiple areas

### ISSUE THREAD

**Issue by igitur** [spreadsheetlab/XLParser#58]
A named range can have multiple areas, e.g. 
`=Sheet1!$A$1:$A$15,Sheet1!$G$1:$G$15`
and currently the parser chokes on this.

My workaround is to wrap it in parenthesis. The parser returns it as a formula, but at least the 'arguments' are parsed.

I was using the online demo for testing.

**Comment by dhoepelman** [comment]
Unfortunately, this is a known bug in the parser, due to limitations of the underlying Irony parser and the LALR parsing algorithm it uses.
Luckily the union syntax (`Range,Range`) is very, very rare, we encountered it only 15 times in a million formuilas.

Your workaround is indeed correct, not that we see the `,` as the binary operation "union", with the 2 ranges as its arguments, so thats why you got that.
