### ISSUE TITLE
Range in R1C1 Format

### ISSUE THREAD

**Issue by mikaboz** [spreadsheetlab/XLParser#79]
In cell B4, I have formula =SOMME(C5:C7)

I'm using closedXML to get the formula in R1C1 format: SUM(R[1]C[1]:R[3]C[1])

In the tree, it seems that ":" has priority over the reference

Assuming I would replace ":" by a function RangeReference( ref1, ref2), 

Then I should get SUM(RangeReference(ref1,ref2)),
instead of  SUM(R[1]RangeReference(C[2],R[3])C[1])

Hope someone can provide me help about it.

Thanks !

**Comment by roelvandersteen** [comment]
As far as I know, XLParser only uses the A1 reference style. If you attempt to parse a formula using the R1C1 reference style, you will get an incorrect parse tree. Manipulation of an incorrect parse tree probably leads to unexpected results.

So you need to use the `IXLCell.FormulaA1` property instead of `IXLCell.FormulaR1C1`.

If you want to modify the argument of a function, you should replace the argument node, which is higher in the tree than the reference node.
