### ISSUE TITLE
NuGet version vs GitHub release version and tags

### ISSUE THREAD

**Issue by igitur** [spreadsheetlab/XLParser#80]
Hi,

I notice that the version on NuGet is `1.3.6`, but the latest release on GitHub is `1.3.4`. That's OK, but it's more troublesome that there is no git tag for `1.3.6`. I would like to checkout the code at the same commit at which `1.3.6` was released. 

Is it possible to bring the repository up to date with the NuGet release?

thanks

**Comment by roelvandersteen** [comment]
There is currently some confusion around the rights administration of this project. That's why I have been making the NuGet releases from this fork: [https://github.com/roelvandersteen/XLParser](https://github.com/roelvandersteen/XLParser), which contains all the recents commits and tags.

When all internal things are sorted out, we will merge the fork in the main repository again.
