### ISSUE TITLE
Union Does Not Work

### ISSUE THREAD

**Issue by hwaller96** [spreadsheetlab/XLParser#98]
When defining a range name, the user will sometimes refer to a disjoint selection, say: 

=A1:A5,C1:C5,E1:E5

And then index this using the area argument of the index function.

The parser does not work on this type of formula, which is legal for Excel rangenames.

**Comment by roelvandersteen** [comment]
Confirmed.

You can use the comma as an union operator in a formula if you use parentheses.

```
=INDEX((A1:A3,C1:C3),1,1,2)
```

(This formula results in the value of cell `C1`.)

The union operator without parentheses is only allowed when defining a name:

```
=A1:A3,C1:C3
```

It gives a `#VALUE!` error when entered in a regular cell. XLParser cannot parse it.

Note that XLParser correctly parses the equivalent formula

```
=(A1:A3,C1:C3)
```

**Comment by WillemJann** [comment]
A new token `MultiRangeFormula` is added to the grammar, that accepts formulas with a union of ranges. `=A1,A2`, `=A1:A3,C1:C3` and `=Sheet1!$A$1,Sheet1!$B$2` are now valid formulas for XLParser.

(Note that this type of formula must start with an equal sign, to avoid conflicts in the grammar. When you define a name like this in Excel, the formula will automatically start with an equal sign.)

Issue is fixed in commit e11dfb5.
